"""Build the URSUS Link support card and localized support pages only."""

from __future__ import annotations

from html import escape
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]

LOCALES = {
    "": ("en", "en"), "ko": ("ko", "ko"), "ja": ("ja", "ja"),
    "zh-cn": ("zh-CN", "zh-CN"), "zh-tw": ("zh-Hant", "zh-TW"),
    "es": ("es", "es"), "fr": ("fr", "fr"), "de": ("de", "de"),
    "it": ("it", "it"), "pt-br": ("pt-BR", "pt-BR"), "id": ("id", "id"),
    "th": ("th", "th"), "vi": ("vi", "vi"), "tr": ("tr", "tr"),
    "hi": ("hi", "hi"), "pl": ("pl", "pl"),
}

COPY = {
"": dict(support="Support", back="Back to Support", icon="app icon", card="Share files directly from your PC; recipients download in a browser.", view="View URSUS Link support", hero="Help for sharing files directly from your Windows PC.", start_h="Getting started", intro="URSUS Link shares files from a folder on your PC directly to a recipient's browser. Files are not uploaded to URSUS Loft cloud storage.", steps=["Choose Shared Folder.", "Review or change the four-digit Password.", "Select Start Sharing.", "Wait for the Share Link to be created.", "Send the Share Link and password to the recipient.", "The recipient opens the link, enters the PIN/password, and downloads the files.", "Select Stop Sharing when you are finished."], link_h="Share link and browser downloads", link_p="The recipient does not need URSUS Link installed. A current web browser is enough. Keep the Share Link and password private, and keep the sender PC online while sharing.", security_h="HTTPS and HTTP fallback", security_p="URSUS Link normally prepares HTTPS and makes up to three eligible setup attempts. If HTTPS still cannot be prepared, you may explicitly choose HTTP fallback. That sharing session is not encrypted in transit.", files_h="Large files and background sharing", files_p="Large files stream from disk and support Range/resume requests. Folder downloads may use a temporary local ZIP64 package. URSUS Link can remain available from the system tray while sharing; keep the app and PC running until transfers finish.", trouble_h="Connection troubleshooting", trouble_p="If the link cannot be opened, confirm that sharing is active, copy the current link again, keep the sender PC online, and allow Windows Firewall access when prompted. Some routers, CGNAT, corporate, public, or mobile networks can block direct incoming connections.", contact_h="Contact support", contact_p="For URSUS Link support, contact {email}.", privacy_h="Privacy", privacy="Privacy Policy"),
"ko": dict(support="지원", back="지원으로 돌아가기", icon="앱 아이콘", card="PC에서 파일을 직접 공유하면 받는 사람은 브라우저에서 다운로드할 수 있습니다.", view="URSUS Link 지원 보기", hero="Windows PC에서 파일을 직접 공유하는 방법을 안내합니다.", start_h="시작하기", intro="URSUS Link는 PC에서 선택한 폴더의 파일을 받는 사람의 브라우저로 직접 공유합니다. 파일은 URSUS Loft 클라우드 저장소에 업로드되지 않습니다.", steps=["Shared Folder를 선택합니다.", "4자리 Password를 확인하거나 변경합니다.", "Start Sharing을 선택합니다.", "Share Link가 생성될 때까지 기다립니다.", "Share Link와 비밀번호를 받는 사람에게 전달합니다.", "받는 사람은 링크를 열고 PIN/비밀번호를 입력한 뒤 파일을 다운로드합니다.", "완료되면 Stop Sharing을 선택합니다."], link_h="공유 링크와 브라우저 다운로드", link_p="받는 사람은 URSUS Link를 설치할 필요가 없으며 최신 웹 브라우저만 있으면 됩니다. Share Link와 비밀번호는 비공개로 전달하고 공유 중에는 보내는 사람의 PC를 온라인 상태로 유지하세요.", security_h="HTTPS와 HTTP fallback", security_p="URSUS Link는 기본적으로 HTTPS를 준비하며 해당하는 경우 최대 세 번 시도합니다. 그래도 HTTPS를 준비할 수 없으면 사용자가 명시적으로 HTTP fallback을 선택할 수 있습니다. 이 공유 세션은 전송 중 암호화되지 않습니다.", files_h="대용량 파일과 백그라운드 공유", files_p="대용량 파일은 디스크에서 스트리밍되며 Range/이어받기 요청을 지원합니다. 폴더 다운로드에는 임시 로컬 ZIP64 패키지가 사용될 수 있습니다. 공유 중에는 시스템 트레이에서 계속 실행할 수 있으며 전송이 끝날 때까지 앱과 PC를 켜 두세요.", trouble_h="연결 문제 해결", trouble_p="링크가 열리지 않으면 공유가 활성 상태인지 확인하고 현재 링크를 다시 복사한 뒤 보내는 사람의 PC를 온라인 상태로 유지하세요. 요청 시 Windows Firewall 접근을 허용해야 합니다. 일부 라우터, CGNAT, 회사·공용·모바일 네트워크는 직접 연결을 차단할 수 있습니다.", contact_h="지원 문의", contact_p="URSUS Link 지원 문의는 {email}으로 보내주세요.", privacy_h="개인정보", privacy="개인정보처리방침"),
"ja": dict(support="サポート", back="サポートに戻る", icon="アプリアイコン", card="PCからファイルを直接共有し、受信者はブラウザーでダウンロードできます。", view="URSUS Linkのサポートを見る", hero="Windows PCからファイルを直接共有するためのヘルプです。", start_h="はじめに", intro="URSUS Linkは、PCで選択したフォルダーのファイルを受信者のブラウザーへ直接共有します。ファイルはURSUS Loftのクラウドストレージへアップロードされません。", steps=["Shared Folderを選択します。", "4桁のPasswordを確認または変更します。", "Start Sharingを選択します。", "Share Linkが作成されるまで待ちます。", "Share Linkとパスワードを受信者へ送ります。", "受信者はリンクを開き、PIN／パスワードを入力してファイルをダウンロードします。", "完了したらStop Sharingを選択します。"], link_h="共有リンクとブラウザーダウンロード", link_p="受信者はURSUS Linkをインストールする必要がなく、最新のWebブラウザーだけで利用できます。Share Linkとパスワードは非公開で送り、共有中は送信側PCをオンラインに保ってください。", security_h="HTTPSとHTTPフォールバック", security_p="URSUS Linkは通常HTTPSの準備を行い、対象となる失敗時には最大3回再試行します。それでもHTTPSを準備できない場合、ユーザーが明示的にHTTPフォールバックを選択できます。その共有セッションの通信は暗号化されません。", files_h="大容量ファイルとバックグラウンド共有", files_p="大容量ファイルはディスクからストリーミングされ、Range／再開リクエストに対応します。フォルダーのダウンロードでは一時的なローカルZIP64パッケージを使用する場合があります。共有中はシステムトレイで動作を続けられます。転送が終わるまでアプリとPCを起動したままにしてください。", trouble_h="接続のトラブルシューティング", trouble_p="リンクを開けない場合は、共有が有効か確認し、現在のリンクを再度コピーして、送信側PCをオンラインに保ってください。求められた場合はWindows Firewallを許可します。一部のルーター、CGNAT、企業・公共・モバイルネットワークでは直接接続が遮断されることがあります。", contact_h="サポートへのお問い合わせ", contact_p="URSUS Linkのサポートは{email}へお問い合わせください。", privacy_h="プライバシー", privacy="プライバシーポリシー"),
"zh-cn": dict(support="支持", back="返回支持", icon="应用图标", card="直接从电脑共享文件，接收方可在浏览器中下载。", view="查看 URSUS Link 支持", hero="帮助您直接从 Windows 电脑共享文件。", start_h="开始使用", intro="URSUS Link 将电脑中所选文件夹的文件直接共享到接收方的浏览器。文件不会上传到 URSUS Loft 云存储。", steps=["选择 Shared Folder。", "确认或更改四位 Password。", "选择 Start Sharing。", "等待 Share Link 创建完成。", "将 Share Link 和密码发送给接收方。", "接收方打开链接，输入 PIN/密码并下载文件。", "完成后选择 Stop Sharing。"], link_h="共享链接与浏览器下载", link_p="接收方无需安装 URSUS Link，只需使用现代网页浏览器。请私下发送 Share Link 和密码，并在共享期间保持发送方电脑在线。", security_h="HTTPS 与 HTTP 回退", security_p="URSUS Link 通常会准备 HTTPS，并在符合条件的设置失败时最多重试三次。如果仍无法准备 HTTPS，用户可以明确选择 HTTP 回退；该共享会话的传输不会加密。", files_h="大文件与后台共享", files_p="大文件从磁盘流式传输，并支持 Range/续传请求。文件夹下载可能使用本地临时 ZIP64 包。共享时 URSUS Link 可在系统托盘中继续运行；请保持应用和电脑运行，直至传输完成。", trouble_h="连接故障排除", trouble_p="如果链接无法打开，请确认共享仍在进行，重新复制当前链接，并保持发送方电脑在线。系统提示时请允许 Windows Firewall 访问。某些路由器、CGNAT、企业、公共或移动网络可能会阻止直接入站连接。", contact_h="联系支持", contact_p="如需 URSUS Link 支持，请联系 {email}。", privacy_h="隐私", privacy="隐私政策"),
"zh-tw": dict(support="支援", back="返回支援", icon="應用程式圖示", card="直接從電腦分享檔案，接收者可在瀏覽器中下載。", view="查看 URSUS Link 支援", hero="協助您直接從 Windows 電腦分享檔案。", start_h="開始使用", intro="URSUS Link 會將電腦所選資料夾中的檔案直接分享至接收者的瀏覽器。檔案不會上傳至 URSUS Loft 雲端儲存空間。", steps=["選擇 Shared Folder。", "確認或變更四位數 Password。", "選擇 Start Sharing。", "等待 Share Link 建立完成。", "將 Share Link 與密碼傳送給接收者。", "接收者開啟連結、輸入 PIN／密碼並下載檔案。", "完成後選擇 Stop Sharing。"], link_h="分享連結與瀏覽器下載", link_p="接收者不需要安裝 URSUS Link，只要使用現代網頁瀏覽器即可。請私下傳送 Share Link 與密碼，並在分享期間讓傳送端電腦保持連線。", security_h="HTTPS 與 HTTP fallback", security_p="URSUS Link 通常會準備 HTTPS，並在符合條件的設定失敗時最多重試三次。若仍無法準備 HTTPS，使用者可以明確選擇 HTTP fallback；該分享工作階段的傳輸不會加密。", files_h="大型檔案與背景分享", files_p="大型檔案會從磁碟串流傳輸，並支援 Range／續傳要求。下載資料夾時可能會使用本機暫存 ZIP64 封裝。分享期間 URSUS Link 可在系統匣中繼續執行；請保持應用程式與電腦運作直到傳輸完成。", trouble_h="連線疑難排解", trouble_p="若連結無法開啟，請確認分享仍在進行、重新複製目前連結，並讓傳送端電腦保持連線。系統提示時請允許 Windows Firewall 存取。部分路由器、CGNAT、企業、公用或行動網路可能會封鎖直接連入連線。", contact_h="聯絡支援", contact_p="如需 URSUS Link 支援，請聯絡 {email}。", privacy_h="隱私權", privacy="隱私權政策"),
"es": dict(support="Soporte", back="Volver a Soporte", icon="icono de la aplicación", card="Comparte archivos directamente desde tu PC; el destinatario los descarga en el navegador.", view="Ver soporte de URSUS Link", hero="Ayuda para compartir archivos directamente desde un PC con Windows.", start_h="Primeros pasos", intro="URSUS Link comparte los archivos de una carpeta de tu PC directamente con el navegador del destinatario. Los archivos no se suben al almacenamiento en la nube de URSUS Loft.", steps=["Elige Shared Folder.", "Comprueba o cambia la Password de cuatro dígitos.", "Selecciona Start Sharing.", "Espera a que se cree el Share Link.", "Envía el Share Link y la contraseña al destinatario.", "El destinatario abre el enlace, introduce el PIN o la contraseña y descarga los archivos.", "Selecciona Stop Sharing cuando termines."], link_h="Enlace compartido y descargas en el navegador", link_p="El destinatario no necesita instalar URSUS Link; basta con un navegador web actual. Envía el Share Link y la contraseña de forma privada y mantén conectado el PC remitente mientras compartes.", security_h="HTTPS y alternativa HTTP", security_p="URSUS Link prepara normalmente HTTPS y reintenta hasta tres veces los fallos de configuración aplicables. Si HTTPS sigue sin estar disponible, puedes elegir explícitamente la alternativa HTTP. Esa sesión no estará cifrada durante la transferencia.", files_h="Archivos grandes y uso en segundo plano", files_p="Los archivos grandes se transmiten desde el disco y admiten solicitudes Range y reanudación. Las descargas de carpetas pueden usar un paquete ZIP64 local temporal. URSUS Link puede seguir disponible desde la bandeja del sistema; mantén la aplicación y el PC encendidos hasta terminar.", trouble_h="Solución de problemas de conexión", trouble_p="Si el enlace no abre, confirma que la sesión sigue activa, vuelve a copiar el enlace actual y mantén conectado el PC remitente. Permite el acceso de Windows Firewall cuando se solicite. Algunos routers, CGNAT y redes corporativas, públicas o móviles pueden bloquear conexiones directas entrantes.", contact_h="Contactar con soporte", contact_p="Para obtener soporte de URSUS Link, escribe a {email}.", privacy_h="Privacidad", privacy="Política de privacidad"),
"fr": dict(support="Assistance", back="Retour à l'assistance", icon="icône de l'application", card="Partagez des fichiers directement depuis votre PC; le destinataire les télécharge dans son navigateur.", view="Voir l'assistance URSUS Link", hero="Aide au partage direct de fichiers depuis un PC Windows.", start_h="Bien démarrer", intro="URSUS Link partage les fichiers d'un dossier de votre PC directement avec le navigateur du destinataire. Les fichiers ne sont pas téléversés vers un stockage cloud URSUS Loft.", steps=["Choisissez Shared Folder.", "Vérifiez ou modifiez le Password à quatre chiffres.", "Sélectionnez Start Sharing.", "Attendez la création du Share Link.", "Envoyez le Share Link et le mot de passe au destinataire.", "Le destinataire ouvre le lien, saisit le PIN ou le mot de passe et télécharge les fichiers.", "Sélectionnez Stop Sharing lorsque vous avez terminé."], link_h="Lien de partage et téléchargement dans le navigateur", link_p="Le destinataire n'a pas besoin d'installer URSUS Link; un navigateur web récent suffit. Transmettez le Share Link et le mot de passe en privé et gardez le PC émetteur en ligne pendant le partage.", security_h="HTTPS et repli HTTP", security_p="URSUS Link prépare normalement une connexion HTTPS et réessaie jusqu'à trois fois en cas d'échec admissible. Si HTTPS reste indisponible, vous pouvez choisir explicitement le repli HTTP. Cette session ne sera pas chiffrée pendant le transfert.", files_h="Fichiers volumineux et partage en arrière-plan", files_p="Les fichiers volumineux sont diffusés depuis le disque et acceptent les requêtes Range/reprise. Le téléchargement d'un dossier peut utiliser une archive ZIP64 locale temporaire. URSUS Link peut rester disponible dans la zone de notification; gardez l'application et le PC allumés jusqu'à la fin.", trouble_h="Résoudre les problèmes de connexion", trouble_p="Si le lien ne s'ouvre pas, vérifiez que le partage est actif, recopiez le lien actuel et gardez le PC émetteur en ligne. Autorisez Windows Firewall lorsque vous y êtes invité. Certains routeurs, CGNAT et réseaux d'entreprise, publics ou mobiles peuvent bloquer les connexions directes entrantes.", contact_h="Contacter l'assistance", contact_p="Pour obtenir de l'aide sur URSUS Link, écrivez à {email}.", privacy_h="Confidentialité", privacy="Politique de confidentialité"),
"de": dict(support="Support", back="Zurück zum Support", icon="App-Symbol", card="Dateien direkt vom PC teilen; Empfänger laden sie im Browser herunter.", view="URSUS Link Support anzeigen", hero="Hilfe zum direkten Teilen von Dateien von einem Windows-PC.", start_h="Erste Schritte", intro="URSUS Link teilt Dateien aus einem Ordner auf Ihrem PC direkt mit dem Browser des Empfängers. Die Dateien werden nicht in einen URSUS Loft Cloud-Speicher hochgeladen.", steps=["Wählen Sie Shared Folder.", "Prüfen oder ändern Sie das vierstellige Password.", "Wählen Sie Start Sharing.", "Warten Sie, bis der Share Link erstellt wurde.", "Senden Sie Share Link und Passwort an den Empfänger.", "Der Empfänger öffnet den Link, gibt PIN/Passwort ein und lädt die Dateien herunter.", "Wählen Sie danach Stop Sharing."], link_h="Freigabelink und Browser-Downloads", link_p="Der Empfänger muss URSUS Link nicht installieren; ein aktueller Webbrowser genügt. Senden Sie Share Link und Passwort privat und lassen Sie den sendenden PC während der Freigabe online.", security_h="HTTPS und HTTP-Fallback", security_p="URSUS Link richtet normalerweise HTTPS ein und wiederholt geeignete fehlgeschlagene Versuche bis zu dreimal. Ist HTTPS weiterhin nicht möglich, können Sie ausdrücklich den HTTP-Fallback wählen. Diese Sitzung ist während der Übertragung nicht verschlüsselt.", files_h="Große Dateien und Freigabe im Hintergrund", files_p="Große Dateien werden von der Festplatte gestreamt und unterstützen Range-/Fortsetzungsanfragen. Ordnerdownloads können ein temporäres lokales ZIP64-Paket verwenden. URSUS Link kann während der Freigabe im Infobereich weiterlaufen; lassen Sie App und PC bis zum Abschluss eingeschaltet.", trouble_h="Verbindungsprobleme beheben", trouble_p="Wenn sich der Link nicht öffnen lässt, prüfen Sie die aktive Freigabe, kopieren Sie den aktuellen Link erneut und lassen Sie den sendenden PC online. Erlauben Sie den Zugriff durch Windows Firewall, wenn Sie dazu aufgefordert werden. Manche Router, CGNAT sowie Firmen-, öffentliche oder Mobilfunknetze blockieren direkte eingehende Verbindungen.", contact_h="Support kontaktieren", contact_p="URSUS Link Support erhalten Sie unter {email}.", privacy_h="Datenschutz", privacy="Datenschutzerklärung"),
"it": dict(support="Assistenza", back="Torna all'assistenza", icon="icona dell'app", card="Condividi file direttamente dal PC; il destinatario li scarica nel browser.", view="Vedi assistenza URSUS Link", hero="Assistenza per condividere file direttamente da un PC Windows.", start_h="Per iniziare", intro="URSUS Link condivide i file di una cartella del PC direttamente con il browser del destinatario. I file non vengono caricati in uno spazio cloud URSUS Loft.", steps=["Scegli Shared Folder.", "Controlla o modifica la Password a quattro cifre.", "Seleziona Start Sharing.", "Attendi la creazione del Share Link.", "Invia Share Link e password al destinatario.", "Il destinatario apre il link, inserisce il PIN o la password e scarica i file.", "Al termine seleziona Stop Sharing."], link_h="Link di condivisione e download nel browser", link_p="Il destinatario non deve installare URSUS Link; basta un browser web aggiornato. Invia Share Link e password in privato e mantieni online il PC del mittente durante la condivisione.", security_h="HTTPS e fallback HTTP", security_p="URSUS Link prepara normalmente HTTPS e ripete fino a tre volte gli errori di configurazione idonei. Se HTTPS non è ancora disponibile, puoi scegliere esplicitamente il fallback HTTP. Quella sessione non sarà cifrata durante il trasferimento.", files_h="File di grandi dimensioni e condivisione in background", files_p="I file grandi vengono trasmessi dal disco e supportano richieste Range/ripresa. Il download di cartelle può usare un pacchetto ZIP64 locale temporaneo. URSUS Link può restare disponibile nell'area di notifica; mantieni app e PC accesi fino al termine.", trouble_h="Risoluzione dei problemi di connessione", trouble_p="Se il link non si apre, verifica che la condivisione sia attiva, copia di nuovo il link corrente e mantieni online il PC del mittente. Consenti l'accesso di Windows Firewall quando richiesto. Alcuni router, CGNAT e reti aziendali, pubbliche o mobili possono bloccare le connessioni dirette in ingresso.", contact_h="Contatta l'assistenza", contact_p="Per l'assistenza di URSUS Link, scrivi a {email}.", privacy_h="Privacy", privacy="Informativa sulla privacy"),
"pt-br": dict(support="Suporte", back="Voltar ao suporte", icon="ícone do aplicativo", card="Compartilhe arquivos diretamente do PC; quem recebe baixa pelo navegador.", view="Ver suporte do URSUS Link", hero="Ajuda para compartilhar arquivos diretamente de um PC Windows.", start_h="Primeiros passos", intro="O URSUS Link compartilha arquivos de uma pasta do seu PC diretamente com o navegador de quem recebe. Os arquivos não são enviados para um armazenamento em nuvem da URSUS Loft.", steps=["Escolha Shared Folder.", "Confira ou altere a Password de quatro dígitos.", "Selecione Start Sharing.", "Aguarde a criação do Share Link.", "Envie o Share Link e a senha para quem vai receber.", "A pessoa abre o link, informa o PIN ou a senha e baixa os arquivos.", "Ao terminar, selecione Stop Sharing."], link_h="Link de compartilhamento e download no navegador", link_p="Quem recebe não precisa instalar o URSUS Link; basta um navegador moderno. Envie o Share Link e a senha de forma privada e mantenha o PC remetente online durante o compartilhamento.", security_h="HTTPS e fallback para HTTP", security_p="O URSUS Link normalmente prepara HTTPS e repete em até três vezes as falhas de configuração aplicáveis. Se o HTTPS ainda não puder ser preparado, você poderá escolher explicitamente o fallback para HTTP. Essa sessão não será criptografada durante a transmissão.", files_h="Arquivos grandes e compartilhamento em segundo plano", files_p="Arquivos grandes são transmitidos do disco e aceitam solicitações Range/retomada. O download de pastas pode usar um pacote ZIP64 local temporário. O URSUS Link pode continuar disponível na bandeja do sistema; mantenha o aplicativo e o PC ligados até o fim.", trouble_h="Solução de problemas de conexão", trouble_p="Se o link não abrir, confirme que o compartilhamento está ativo, copie novamente o link atual e mantenha o PC remetente online. Permita o acesso do Windows Firewall quando solicitado. Alguns roteadores, CGNAT e redes corporativas, públicas ou móveis podem bloquear conexões diretas de entrada.", contact_h="Fale com o suporte", contact_p="Para suporte do URSUS Link, escreva para {email}.", privacy_h="Privacidade", privacy="Política de Privacidade"),
"id": dict(support="Dukungan", back="Kembali ke Dukungan", icon="ikon aplikasi", card="Bagikan file langsung dari PC; penerima mengunduhnya di browser.", view="Lihat dukungan URSUS Link", hero="Bantuan untuk berbagi file langsung dari PC Windows.", start_h="Memulai", intro="URSUS Link membagikan file dari folder di PC Anda langsung ke browser penerima. File tidak diunggah ke penyimpanan cloud URSUS Loft.", steps=["Pilih Shared Folder.", "Periksa atau ubah Password empat digit.", "Pilih Start Sharing.", "Tunggu hingga Share Link dibuat.", "Kirim Share Link dan kata sandi kepada penerima.", "Penerima membuka tautan, memasukkan PIN/kata sandi, lalu mengunduh file.", "Pilih Stop Sharing setelah selesai."], link_h="Tautan berbagi dan unduhan browser", link_p="Penerima tidak perlu memasang URSUS Link; browser web modern sudah cukup. Kirim Share Link dan kata sandi secara pribadi serta biarkan PC pengirim tetap online selama berbagi.", security_h="HTTPS dan fallback HTTP", security_p="URSUS Link biasanya menyiapkan HTTPS dan mencoba ulang kegagalan penyiapan yang memenuhi syarat hingga tiga kali. Jika HTTPS masih tidak dapat disiapkan, Anda dapat memilih fallback HTTP secara tegas. Sesi tersebut tidak dienkripsi selama pengiriman.", files_h="File besar dan berbagi di latar belakang", files_p="File besar dialirkan dari disk serta mendukung permintaan Range/lanjutkan. Unduhan folder dapat memakai paket ZIP64 lokal sementara. URSUS Link dapat tetap tersedia dari baki sistem; biarkan aplikasi dan PC menyala sampai transfer selesai.", trouble_h="Pemecahan masalah koneksi", trouble_p="Jika tautan tidak dapat dibuka, pastikan berbagi masih aktif, salin ulang tautan terkini, dan biarkan PC pengirim tetap online. Izinkan akses Windows Firewall saat diminta. Beberapa router, CGNAT, serta jaringan perusahaan, publik, atau seluler dapat memblokir koneksi langsung yang masuk.", contact_h="Hubungi dukungan", contact_p="Untuk dukungan URSUS Link, hubungi {email}.", privacy_h="Privasi", privacy="Kebijakan Privasi"),
"th": dict(support="ฝ่ายสนับสนุน", back="กลับไปหน้าฝ่ายสนับสนุน", icon="ไอคอนแอป", card="แชร์ไฟล์โดยตรงจากพีซี ผู้รับดาวน์โหลดผ่านเบราว์เซอร์ได้", view="ดูฝ่ายสนับสนุน URSUS Link", hero="วิธีแชร์ไฟล์โดยตรงจากพีซี Windows", start_h="เริ่มต้นใช้งาน", intro="URSUS Link แชร์ไฟล์จากโฟลเดอร์ที่เลือกบนพีซีไปยังเบราว์เซอร์ของผู้รับโดยตรง โดยไม่อัปโหลดไฟล์ไปยังพื้นที่เก็บข้อมูลคลาวด์ของ URSUS Loft", steps=["เลือก Shared Folder", "ตรวจสอบหรือเปลี่ยน Password 4 หลัก", "เลือก Start Sharing", "รอให้สร้าง Share Link", "ส่ง Share Link และรหัสผ่านให้ผู้รับ", "ผู้รับเปิดลิงก์ ป้อน PIN/รหัสผ่าน แล้วดาวน์โหลดไฟล์", "เมื่อเสร็จแล้วให้เลือก Stop Sharing"], link_h="ลิงก์แชร์และการดาวน์โหลดในเบราว์เซอร์", link_p="ผู้รับไม่ต้องติดตั้ง URSUS Link เพียงมีเว็บเบราว์เซอร์รุ่นใหม่ ส่ง Share Link และรหัสผ่านเป็นการส่วนตัว และให้พีซีของผู้ส่งออนไลน์อยู่ระหว่างการแชร์", security_h="HTTPS และการใช้ HTTP สำรอง", security_p="โดยปกติ URSUS Link จะเตรียม HTTPS และลองใหม่สำหรับข้อผิดพลาดที่เข้าเงื่อนไขสูงสุดสามครั้ง หากยังเตรียม HTTPS ไม่ได้ ผู้ใช้สามารถเลือกใช้ HTTP สำรองอย่างชัดเจนได้ เซสชันนั้นจะไม่เข้ารหัสข้อมูลระหว่างส่ง", files_h="ไฟล์ขนาดใหญ่และการแชร์เบื้องหลัง", files_p="ไฟล์ขนาดใหญ่จะสตรีมจากดิสก์และรองรับคำขอ Range/ทำต่อ การดาวน์โหลดโฟลเดอร์อาจใช้แพ็กเกจ ZIP64 ชั่วคราวในเครื่อง URSUS Link ทำงานต่อจากถาดระบบได้ระหว่างแชร์ โปรดเปิดแอปและพีซีไว้จนกว่าจะถ่ายโอนเสร็จ", trouble_h="แก้ไขปัญหาการเชื่อมต่อ", trouble_p="หากเปิดลิงก์ไม่ได้ ให้ตรวจสอบว่ากำลังแชร์อยู่ คัดลอกลิงก์ปัจจุบันอีกครั้ง และให้พีซีผู้ส่งออนไลน์ อนุญาต Windows Firewall เมื่อระบบถาม เราเตอร์บางรุ่น, CGNAT หรือเครือข่ายองค์กร สาธารณะ และมือถืออาจปิดกั้นการเชื่อมต่อขาเข้าโดยตรง", contact_h="ติดต่อฝ่ายสนับสนุน", contact_p="หากต้องการความช่วยเหลือเกี่ยวกับ URSUS Link โปรดติดต่อ {email}", privacy_h="ความเป็นส่วนตัว", privacy="นโยบายความเป็นส่วนตัว"),
"vi": dict(support="Hỗ trợ", back="Quay lại Hỗ trợ", icon="biểu tượng ứng dụng", card="Chia sẻ tệp trực tiếp từ PC; người nhận tải xuống bằng trình duyệt.", view="Xem hỗ trợ URSUS Link", hero="Hướng dẫn chia sẻ tệp trực tiếp từ PC Windows.", start_h="Bắt đầu", intro="URSUS Link chia sẻ tệp từ một thư mục trên PC trực tiếp tới trình duyệt của người nhận. Tệp không được tải lên kho lưu trữ đám mây của URSUS Loft.", steps=["Chọn Shared Folder.", "Kiểm tra hoặc đổi Password gồm bốn chữ số.", "Chọn Start Sharing.", "Chờ Share Link được tạo.", "Gửi Share Link và mật khẩu cho người nhận.", "Người nhận mở liên kết, nhập PIN/mật khẩu rồi tải tệp xuống.", "Chọn Stop Sharing khi hoàn tất."], link_h="Liên kết chia sẻ và tải xuống bằng trình duyệt", link_p="Người nhận không cần cài URSUS Link; chỉ cần trình duyệt web hiện đại. Hãy gửi riêng Share Link và mật khẩu, đồng thời giữ PC của người gửi trực tuyến trong lúc chia sẻ.", security_h="HTTPS và phương án HTTP", security_p="URSUS Link thường chuẩn bị HTTPS và thử lại tối đa ba lần với các lỗi thiết lập phù hợp. Nếu vẫn không thể chuẩn bị HTTPS, bạn có thể chủ động chọn phương án HTTP. Phiên chia sẻ đó không được mã hóa khi truyền.", files_h="Tệp lớn và chia sẻ nền", files_p="Tệp lớn được truyền trực tiếp từ đĩa và hỗ trợ yêu cầu Range/tiếp tục. Tải thư mục có thể dùng gói ZIP64 cục bộ tạm thời. URSUS Link có thể tiếp tục chạy trong khay hệ thống; hãy giữ ứng dụng và PC hoạt động đến khi truyền xong.", trouble_h="Khắc phục sự cố kết nối", trouble_p="Nếu không mở được liên kết, hãy xác nhận chia sẻ còn hoạt động, sao chép lại liên kết hiện tại và giữ PC người gửi trực tuyến. Cho phép Windows Firewall khi được hỏi. Một số router, CGNAT và mạng doanh nghiệp, công cộng hoặc di động có thể chặn kết nối trực tiếp từ bên ngoài.", contact_h="Liên hệ hỗ trợ", contact_p="Để được hỗ trợ về URSUS Link, hãy liên hệ {email}.", privacy_h="Quyền riêng tư", privacy="Chính sách quyền riêng tư"),
"tr": dict(support="Destek", back="Desteğe dön", icon="uygulama simgesi", card="Dosyaları doğrudan PC'nizden paylaşın; alıcı tarayıcıdan indirsin.", view="URSUS Link desteğini görüntüle", hero="Windows PC'den doğrudan dosya paylaşımı için yardım.", start_h="Başlarken", intro="URSUS Link, PC'nizdeki bir klasörün dosyalarını doğrudan alıcının tarayıcısıyla paylaşır. Dosyalar URSUS Loft bulut depolamasına yüklenmez.", steps=["Shared Folder'ı seçin.", "Dört haneli Password'ü kontrol edin veya değiştirin.", "Start Sharing'i seçin.", "Share Link oluşturulana kadar bekleyin.", "Share Link'i ve parolayı alıcıya gönderin.", "Alıcı linki açar, PIN/parolayı girer ve dosyaları indirir.", "İşiniz bittiğinde Stop Sharing'i seçin."], link_h="Paylaşım linki ve tarayıcı indirmeleri", link_p="Alıcının URSUS Link kurması gerekmez; güncel bir web tarayıcısı yeterlidir. Share Link'i ve parolayı özel olarak gönderin, paylaşım sırasında gönderen PC'yi çevrimiçi tutun.", security_h="HTTPS ve HTTP geri dönüşü", security_p="URSUS Link normalde HTTPS hazırlar ve uygun kurulum hatalarını en fazla üç kez yeniden dener. HTTPS yine hazırlanamazsa HTTP geri dönüşünü açıkça seçebilirsiniz. Bu paylaşım oturumu aktarım sırasında şifrelenmez.", files_h="Büyük dosyalar ve arka planda paylaşım", files_p="Büyük dosyalar diskten aktarılır ve Range/devam isteklerini destekler. Klasör indirmeleri geçici yerel bir ZIP64 paketi kullanabilir. URSUS Link paylaşım sırasında sistem tepsisinde çalışmaya devam edebilir; aktarım bitene kadar uygulamayı ve PC'yi açık tutun.", trouble_h="Bağlantı sorunlarını giderme", trouble_p="Link açılmıyorsa paylaşımın etkin olduğunu doğrulayın, güncel linki yeniden kopyalayın ve gönderen PC'yi çevrimiçi tutun. İstendiğinde Windows Firewall erişimine izin verin. Bazı router'lar, CGNAT ile kurumsal, genel veya mobil ağlar doğrudan gelen bağlantıları engelleyebilir.", contact_h="Destekle iletişim", contact_p="URSUS Link desteği için {email} adresine yazın.", privacy_h="Gizlilik", privacy="Gizlilik Politikası"),
"hi": dict(support="सहायता", back="सहायता पर वापस जाएँ", icon="ऐप आइकन", card="सीधे अपने PC से फ़ाइलें साझा करें; प्राप्तकर्ता ब्राउज़र में डाउनलोड करता है।", view="URSUS Link सहायता देखें", hero="Windows PC से सीधे फ़ाइलें साझा करने में सहायता।", start_h="शुरू करना", intro="URSUS Link आपके PC पर चुने गए फ़ोल्डर की फ़ाइलें सीधे प्राप्तकर्ता के ब्राउज़र से साझा करता है। फ़ाइलें URSUS Loft cloud storage पर अपलोड नहीं होतीं।", steps=["Shared Folder चुनें।", "चार अंकों का Password जाँचें या बदलें।", "Start Sharing चुनें।", "Share Link बनने की प्रतीक्षा करें।", "Share Link और पासवर्ड प्राप्तकर्ता को भेजें।", "प्राप्तकर्ता लिंक खोलता है, PIN/पासवर्ड डालता है और फ़ाइलें डाउनलोड करता है।", "पूरा होने पर Stop Sharing चुनें।"], link_h="शेयर लिंक और ब्राउज़र डाउनलोड", link_p="प्राप्तकर्ता को URSUS Link इंस्टॉल करने की आवश्यकता नहीं है; आधुनिक वेब ब्राउज़र पर्याप्त है। Share Link और पासवर्ड निजी रूप से भेजें और साझा करते समय भेजने वाले PC को ऑनलाइन रखें।", security_h="HTTPS और HTTP fallback", security_p="URSUS Link सामान्यतः HTTPS तैयार करता है और योग्य setup failure पर अधिकतम तीन बार फिर कोशिश करता है। HTTPS फिर भी तैयार न हो तो आप स्पष्ट रूप से HTTP fallback चुन सकते हैं। उस sharing session का data transit में encrypted नहीं होगा।", files_h="बड़ी फ़ाइलें और background sharing", files_p="बड़ी फ़ाइलें disk से stream होती हैं और Range/resume request का समर्थन करती हैं। Folder download अस्थायी local ZIP64 package का उपयोग कर सकता है। साझा करते समय URSUS Link system tray में चलता रह सकता है; transfer पूरा होने तक app और PC चालू रखें।", trouble_h="कनेक्शन की समस्या हल करना", trouble_p="यदि लिंक नहीं खुलता, तो sharing सक्रिय होने की पुष्टि करें, वर्तमान लिंक फिर copy करें और भेजने वाले PC को online रखें। पूछे जाने पर Windows Firewall access की अनुमति दें। कुछ router, CGNAT, corporate, public या mobile network सीधे incoming connection को रोक सकते हैं।", contact_h="सहायता से संपर्क", contact_p="URSUS Link सहायता के लिए {email} पर संपर्क करें।", privacy_h="गोपनीयता", privacy="गोपनीयता नीति"),
"pl": dict(support="Pomoc", back="Wróć do pomocy", icon="ikona aplikacji", card="Udostępniaj pliki bezpośrednio z komputera; odbiorca pobiera je w przeglądarce.", view="Zobacz pomoc URSUS Link", hero="Pomoc w bezpośrednim udostępnianiu plików z komputera z Windows.", start_h="Pierwsze kroki", intro="URSUS Link udostępnia pliki z folderu na komputerze bezpośrednio do przeglądarki odbiorcy. Pliki nie są wysyłane do chmury URSUS Loft.", steps=["Wybierz Shared Folder.", "Sprawdź lub zmień czterocyfrowe Password.", "Wybierz Start Sharing.", "Poczekaj na utworzenie Share Link.", "Wyślij Share Link i hasło odbiorcy.", "Odbiorca otwiera link, wpisuje PIN/hasło i pobiera pliki.", "Po zakończeniu wybierz Stop Sharing."], link_h="Link udostępniania i pobieranie w przeglądarce", link_p="Odbiorca nie musi instalować URSUS Link; wystarczy nowoczesna przeglądarka. Wyślij Share Link i hasło prywatnie, a podczas udostępniania utrzymuj komputer nadawcy online.", security_h="HTTPS i tryb awaryjny HTTP", security_p="URSUS Link zwykle przygotowuje HTTPS i ponawia odpowiednie nieudane próby konfiguracji do trzech razy. Jeśli HTTPS nadal nie jest dostępny, możesz świadomie wybrać tryb HTTP. Ta sesja nie będzie szyfrowana podczas transmisji.", files_h="Duże pliki i udostępnianie w tle", files_p="Duże pliki są przesyłane strumieniowo z dysku i obsługują żądania Range/wznawiania. Pobieranie folderu może używać tymczasowego lokalnego pakietu ZIP64. URSUS Link może pozostać dostępny w zasobniku systemowym; pozostaw aplikację i komputer włączone do końca transferu.", trouble_h="Rozwiązywanie problemów z połączeniem", trouble_p="Jeśli link się nie otwiera, sprawdź, czy udostępnianie jest aktywne, ponownie skopiuj bieżący link i utrzymuj komputer nadawcy online. Po wyświetleniu monitu zezwól na dostęp przez Windows Firewall. Niektóre routery, CGNAT oraz sieci firmowe, publiczne lub komórkowe mogą blokować bezpośrednie połączenia przychodzące.", contact_h="Kontakt z pomocą", contact_p="Pomoc dotyczącą URSUS Link uzyskasz pod adresem {email}.", privacy_h="Prywatność", privacy="Polityka prywatności"),
}


def localized_url(prefix: str) -> str:
    return f"https://ursusloft.com/{prefix + '/' if prefix else ''}support/ursus-link.html"


def alternates() -> str:
    links = []
    for prefix, (_, hreflang) in LOCALES.items():
        links.append(f'<link rel="alternate" hreflang="{hreflang}" href="{localized_url(prefix)}">')
    links.append(f'<link rel="alternate" hreflang="x-default" href="{localized_url("")}">')
    return "\n  ".join(links)


def shell_part(source: str, tag: str) -> str:
    match = re.search(rf"<{tag}\b.*?</{tag}>", source, re.S)
    if not match:
        raise ValueError(f"Missing {tag} in source support page")
    return match.group(0)


def support_page(prefix: str, copy: dict) -> str:
    root = ROOT / prefix if prefix else ROOT
    shell = (root / "support" / "scene-director.html").read_text(encoding="utf-8")
    if "<header" not in shell or "<footer" not in shell:
        shell = (root / "support" / "persona-director.html").read_text(encoding="utf-8")
    header = shell_part(shell, "header")
    footer = shell_part(shell, "footer").replace("privacy/scene-director.html", "privacy/ursus-link/index.html")
    asset_prefix = "../../" if prefix else "../"
    title = f"URSUS Link {copy['support']} — URSUS Loft"
    description = copy["hero"]
    steps = "".join(f"<li>{escape(step)}</li>" for step in copy["steps"])
    email = '<a href="mailto:support@ursusloft.com">support@ursusloft.com</a>'
    contact = copy["contact_p"].format(email=email)
    return f'''<!doctype html>
<html lang="{LOCALES[prefix][0]}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <meta name="description" content="{escape(description, quote=True)}">
  <meta property="og:title" content="{escape(title, quote=True)}">
  <meta property="og:description" content="{escape(description, quote=True)}">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{localized_url(prefix)}">
  <meta name="twitter:card" content="summary">
  <link rel="canonical" href="{localized_url(prefix)}">
  {alternates()}
  <link rel="stylesheet" href="{asset_prefix}assets/css/styles.css">
  <script src="{asset_prefix}assets/js/site.js" defer></script>
</head>
<body>
  {header}
  <main>
    <section class="page-hero"><div class="container"><p><a class="text-link" href="index.html">← {escape(copy['back'])}</a></p><p class="eyebrow">URSUS Link</p><h1>{escape(copy['support'])}</h1><p class="product-description">{escape(copy['hero'])}</p></div></section>
    <section class="section"><article class="container prose">
      <section><h2>{escape(copy['start_h'])}</h2><p>{escape(copy['intro'])}</p><ol class="support-list">{steps}</ol></section>
      <section><h2>{escape(copy['link_h'])}</h2><p>{escape(copy['link_p'])}</p></section>
      <section><h2>{escape(copy['security_h'])}</h2><p>{escape(copy['security_p'])}</p></section>
      <section><h2>{escape(copy['files_h'])}</h2><p>{escape(copy['files_p'])}</p></section>
      <section><h2>{escape(copy['trouble_h'])}</h2><p>{escape(copy['trouble_p'])}</p></section>
      <section><h2>{escape(copy['contact_h'])}</h2><p>{contact}</p></section>
      <section><h2>{escape(copy['privacy_h'])}</h2><div class="related-links"><a href="../privacy/ursus-link/index.html">{escape(copy['privacy'])}</a></div></section>
    </article></section>
  </main>
  {footer}
</body>
</html>
'''


def add_card(prefix: str, copy: dict) -> None:
    root = ROOT / prefix if prefix else ROOT
    path = root / "support" / "index.html"
    source = path.read_text(encoding="utf-8")
    asset_prefix = "../../" if prefix else "../"
    card = (
        '<a class="product-card support-product-card" href="ursus-link.html">'
        f'<img class="product-card-icon product-card-icon--ursus-link" src="{asset_prefix}assets/images/ursus-link-icon.png" alt="URSUS Link {escape(copy["icon"], quote=True)}">'
        f'<h3>URSUS Link</h3><p>{escape(copy["card"])}</p>'
        f'<span class="text-link">{escape(copy["view"])} <span aria-hidden="true">→</span></span></a>'
    )
    pattern = re.compile(r'<a class="product-card support-product-card" href="ursus-link\.html">.*?</a>', re.S)
    source = pattern.sub("", source)
    match = re.search(r'(<div class="product-grid support-grid">)(.*?)(</div>)(?=<p(?:\s|>))', source, re.S)
    if not match:
        raise ValueError(f"Support grid not found: {path}")
    source = source[:match.start()] + match.group(1) + match.group(2) + card + match.group(3) + source[match.end():]
    path.write_text(source, encoding="utf-8")


def add_sitemap_routes() -> None:
    path = ROOT / "sitemap.xml"
    source = path.read_text(encoding="utf-8")
    additions = []
    for prefix in LOCALES:
        url = localized_url(prefix)
        if f"<loc>{url}</loc>" not in source:
            additions.append(f"  <url><loc>{url}</loc></url>")
    source = source.replace("</urlset>", "\n".join(additions) + ("\n" if additions else "") + "</urlset>")
    path.write_text(source, encoding="utf-8")


def main() -> None:
    for prefix, copy in COPY.items():
        add_card(prefix, copy)
        target_root = ROOT / prefix if prefix else ROOT
        (target_root / "support" / "ursus-link.html").write_text(support_page(prefix, copy), encoding="utf-8")
    add_sitemap_routes()
    print(f"support_cards={len(COPY)} support_pages={len(COPY)}")


if __name__ == "__main__":
    main()
